### ISSUE TITLE
add ui for changing riding detection settings

### ISSUE THREAD

**Issue by orzechowskikamil** [orzechowskikamil/motoresponder#10]

**Comment by medziku** [comment]
What You mean by 'riding detection' settings? Enabling multiple sensors for example GPS, accelerometer? Or You thought of kind of algorithm mixing it up?

**Comment by orzechowskikamil** [comment]
riding detection settings means parameters of algorithm which decides if user is riding on motorcycle or not. 

this milestone means adding ui for changing those parameters for example speed on which we are sure that user is riding or acceleration value where we assume that user is riding. or settings like "assume unlocked phone as not riding etc"

**Comment by orzechowskikamil** [comment]
done
