### ISSUE TITLE
add text field for setting acceleration values

### ISSUE THREAD

**Issue by orzechowskikamil** [orzechowskikamil/motoresponder#18]

**Comment by medziku** [comment]
What You mean exactly? Can You write criteria of the acceleration settings?

**Comment by orzechowskikamil** [comment]
I mean that thousands of users will be able to find better threshold of ride/not ride acceleration than me. 

my job is to give them enough possibility to setup app to fit their needs. 

I hate applications which are generally nice but doesn't allow me to adjust one parameter which is critical for me and I finally end up with some shitty looking app which allow me to set up everything up to me and fulfill my goals.

**Comment by orzechowskikamil** [comment]
- add also setting to turn on / off accelerometer check
