### ISSUE TITLE
add text field for setting proximity value

### ISSUE THREAD

**Issue by orzechowskikamil** [orzechowskikamil/motoresponder#19]

**Comment by medziku** [comment]
Proximity detector is only to give You nominal data like close, middle and out of range. I wouldn't set it up like metric because it never ment to be a distance meter.

**Comment by orzechowskikamil** [comment]
proximity meter return you values in centimeters as I remember and it's up to you to decide which is close and which is far away.

my phone returns 100.0 for away and 3.0 for close. your probably return different values.

I thought its good idea to allow user adjust it

**Comment by orzechowskikamil** [comment]
not required right now.
