### ISSUE TITLE
normalize phone numbers everywhere before comparing them.

### ISSUE THREAD

**Issue by orzechowskikamil** [orzechowskikamil/motoresponder#33]

**Comment by medziku** [comment]
This will be hard to achieve, because mobile operators use different standards. Some use +48 for default, some use 48, and sometimes one with no country/regional prefix.

**Comment by orzechowskikamil** [comment]
i have a idea how to perform this check. 

we can check which regional prefix is used in this country , and when we begin to check number, we will cut country prefix (for foreign numbers we will cut + / 00 ) and then number like this will be used for query. I guess that android call log (sqlite) allow some regular expressions so we can strip whitespace or dashes from numbers in call log before comparation

**Comment by orzechowskikamil** [comment]
if we do not normalize them we can land in situation when you receive message from +48 Xxx xxx xxx, user responded to xxxxxxxxx after 30 secs but app thinks that those two numbers are different , so it will send auto respond message
