### ISSUE TITLE
make gray icons for notiifications

### ISSUE THREAD

**Issue by orzechowskikamil** [orzechowskikamil/motoresponder#34]

**Comment by medziku** [comment]
Maybe B&W like Google Material Concepts (https://www.google.com/design/spec/patterns/notifications.html#notifications-content - the distinct icons).

We need to convert current icon to B&W.

**Comment by orzechowskikamil** [comment]
i think main icon can be color and actual icon is great. but I read that notification icons for material design must be b&w

**Comment by medziku** [comment]
Exactly. The inner bike should be nice ;)
