### ISSUE TITLE
unregister listeners, receivers properly

### ISSUE THREAD

**Issue by orzechowskikamil** [orzechowskikamil/motoresponder#4]

**Comment by medziku** [comment]
What does it mean? Haven't checked Your code yet, but can You tip me what bothers You?

**Comment by orzechowskikamil** [comment]
just to  make sure that everything is OK, maybe at current state everything is done properly

**Comment by orzechowskikamil** [comment]
starting progress at this

**Comment by orzechowskikamil** [comment]
done
