### ISSUE TITLE
review all todos

### ISSUE THREAD

**Issue by orzechowskikamil** [orzechowskikamil/motoresponder#42]

**Comment by medziku** [comment]
If we use Jenkins we could gather TODO's, FIXME's etc. automatically.

**Comment by orzechowskikamil** [comment]
this task was for me, to review todos and remove already implemented and those one which are not implemented should be put as issues and assigned to milestones

**Comment by orzechowskikamil** [comment]
this task was for me, to review todos and remove already implemented and those one which are not implemented should be put as issues and assigned to milestones

**Comment by orzechowskikamil** [comment]
I am working on this

**Comment by orzechowskikamil** [comment]
Done - all todos left in code are signed with issue number, and issues for them are created (or reused if they already exist), waits for merge.

**Comment by orzechowskikamil** [comment]
merged to orzech.
