### ISSUE TITLE
add ui for viewing log

### ISSUE THREAD

**Issue by orzechowskikamil** [orzechowskikamil/motoresponder#9]

**Comment by medziku** [comment]
U mean Call Log? SMS/MMS log?

**Comment by orzechowskikamil** [comment]
I mean log where user can 'debug' algorithm's decisions like this :

21:20 received SMS from 791791791
21:21 acceleration was 2.0, assumed as no ride because threshold is 5.0 
21:55 received SMS from 791792793
21:55 phone locked,
21:55 acceleration was 15.0 assumed as possible ride 
21:55 GPS speed 279km/h , user assumed as riding
21:56 sending auto response

**Comment by orzechowskikamil** [comment]
so you can review log after ride and set threshold

**Comment by medziku** [comment]
There is no need to display the log. We need only deliver it to us/user. Log file is enough for now.

**Comment by orzechowskikamil** [comment]
hmm? why you think that there is no need to display log? 

do you think that possibility  to review algorithm decisions after 3h motorcycle trip is not convenient? notice that usually you can't play with phone during ride. :)

**Comment by orzechowskikamil** [comment]
BigText notification can be used as UI for this

**Comment by orzechowskikamil** [comment]
already done with other task
